# Generated by Django 4.0.1 on 2022-05-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('icon', models.ImageField(upload_to='uploads/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('worthInD', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('createdOn', models.DateTimeField(verbose_name='Created On')),
                ('worthInD', models.DecimalField(decimal_places=4, max_digits=12)),
                ('image', models.ImageField(upload_to='uploads/nft')),
                ('token', models.TextField(max_length=500)),
                ('summary', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('profilepic', models.ImageField(upload_to='uploads/profile')),
                ('location', models.TextField(max_length=300)),
                ('about', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('priceInD', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='home.profile')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.nft')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to='home.profile')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.profile'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.profile')),
            ],
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountInD', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.BooleanField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.profile')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.currency')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.nft')),
            ],
        ),
    ]
