# Generated by Django 4.0.1 on 2022-05-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='createdOn',
            field=models.DateTimeField(auto_now=True, verbose_name='Created On'),
        ),
    ]
